### ISSUE TITLE
Allow multiple selections in open index maps

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/GeoData#184]
A consideration for @ewlarson in October.  This may be way too ambitious for the week have!

Currently, identifying and downloading items referenced in an open index map in GBL is a one-by-one approach.  That is, you get a tile index, click on a  polygon to see details, then click a link to download.  This works well!

![image](https://user-images.githubusercontent.com/3149952/122603439-ee9e5800-d039-11eb-87cd-8f006936a207.png)

But: very often a user wants to download multiple items for a particular area of interest.  In the current scheme, the user must keep careful mental track of what they've already clicked and downloaded.  It forces them to think too much.

Instead: implement a very simple functionality to allow the user to drag and select multiple tiles.  Perhaps even control-click to add or remove selected items.  The selections are presented as a table instead of a list.  At the end of each row in the table include a button that fires off the download.  After the button is clicked, use javascript to change the graphic to mark is as completed.  (this would not be foolproof, since there is no guarantee the download actually completed.) The intent is to give _some sort_ of visual indicator that they already downloaded that item.

This would be a compromise between a much more complicated clip and ship type of application that goes way beyond GeoBlacklight, and the single-click to download functionality that we currently have.  I  believe this is all mostly doable using standard functionality of leaflet with a little extra JS thrown in.

**Comment by ewlarson** [comment]
Okay... here's a demo of the feature running in the GeoData application. I think this code is in a good place now for you to test locally or on your test server.

![index_map_with_buttons](https://user-images.githubusercontent.com/69827/139493706-8330a37b-7e93-4d59-acde-7448eccb016c.gif)
